
##########################
cloud_enum
github.com/initstring
##########################


Keywords:    sskyroute
Mutations:   /home/skyroute/cloud-1/capstone/capstone/tools/cloud_enum/enum_tools/fuzz.txt
Brute-list:  /home/skyroute/cloud-1/capstone/capstone/tools/cloud_enum/enum_tools/fuzz.txt

[+] Mutations list imported: 3 items
[+] Mutated results: 19 items

++++++++++++++++++++++++++
amazon checks
++++++++++++++++++++++++++

[+] Checking for S3 buckets
[!] Connection error on sskyroute.s3.ap-northeast-2.amazonaws.com:
HTTPConnectionPool(host='sskyroute.s3.ap-northeast-2.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f448724bdf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[!] Connection error on sskyrouteuserdata.s3.ap-northeast-2.amazonaws.com:
HTTPConnectionPool(host='sskyrouteuserdata.s3.ap-northeast-2.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f448724bf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[!] Connection error on sskyroute.userdata.s3.ap-northeast-2.amazonaws.com:
HTTPConnectionPool(host='sskyroute.userdata.s3.ap-northeast-2.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4486213640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[!] Connection error on sskyroute-userdata.s3.ap-northeast-2.amazonaws.com:
HTTPConnectionPool(host='sskyroute-userdata.s3.ap-northeast-2.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f448621e070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[!] Connection error on userdatasskyroute.s3.ap-northeast-2.amazonaws.com:
HTTPConnectionPool(host='userdatasskyroute.s3.ap-northeast-2.amazonaws.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f448621e640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
